# Generated by Django 4.0.3 on 2022-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
